### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by iyudincev** [pastahito/electron-react-webpack#13]
The template won't build on `npm start`, the error follows:
```
/home/osboxes/test/node_modules/webpack-cli/bin/config-yargs.js:89
		describe: optionsSchema.definitions.output.properties.path.description,
		                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/osboxes/test/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /home/osboxes/test/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/home/osboxes/test/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by pratapdd** [comment]
same error..

**Comment by pratapdd** [comment]
downgrading from 4.20.0 to 4.19.0 , worked for me now.

**Comment by iinow** [comment]
I solved it 
"webpack-cli": "^2.0.11" -> "webpack-cli": "^3.1.2"  

webpack update!!!!

**Comment by MrRefactoring** [comment]
I do fix this issue in my pull request #14

**Comment by p32929** [comment]
Perfecto!!

**Comment by abhishekchotaliya** [comment]
@pastahito 
Please update the `package.json` file so that users like me don't need to come to this page for troubleshooting.

**Comment by diegodorado** [comment]
> I do fix this issue in my pull request #14

Please, accept this PR, it does overcome this issue
